### ISSUE TITLE
Full ChexQuest Support?

### ISSUE THREAD

**Issue by RetroGamer02** [doomhack/GBADoom#21]
I decided to try building the popular ChexQuest mod for the GBA and it works but uses the original Doom music and sounds. Would it be reasonable to add full support for this game?

**Comment by Kippykip** [comment]
No this Git is for Doom only. I'd report the issue instead for chexquest fork here: https://bitbucket.org/Mackya/chexquestgba/src/master/
(Although I had a look and they already changed the music and sounds... Are you using the fork or did you just swap the WAD yourself?)

Either way the reasoning it's happening though is the games music and sounds come from the /music subdirectory instead of the WAD file itself. If you change that with chexquest SFX then building Doom would play their SFX instead.

So yeah with any custom WADS you'd also have to change the contents in /music/ yourself, plus edit any DEHACKED modifications by hand.
(I know in chex quest enemies were slightly changed to only shoot when close etc)

**Comment by RetroGamer02** [comment]
I just swaped the wads I had no idea  there was a Chex fork thanks for letting me know.
