### ISSUE TITLE
Question about gfx stbar

### ISSUE THREAD

**Issue by RetroGamer02** [doomhack/GBADoom#34]
Hi could you tell me how I would go about editing the graphic it seems to be in an unusual format. I would like to change it to better fit FreeDoom.

**Comment by Kippykip** [comment]
I believe it's just raw pixel data in source\gfx\stbar.h
Each number represents an index in the PLAYPAL palette from left to right.

The way I quickly converted the Doom 2 Retail hud over, was because it was basically the same format as my .D2I files made for the GBA Doom 2 Retail modding tools. Which is also basically the same format as doom flats but they're not restricted to 64x64.
![image_2022-08-28_115657238](https://user-images.githubusercontent.com/33023808/187054189-55f94586-9f9a-42cd-96c3-e431beba4725.png)

Then I wrote a quick and dirty script where it would read the raw bytes in the .D2I file and output the equivalent number and a comma into a text file. (So $FF would become 255, etc)

**Comment by RetroGamer02** [comment]
I will see if I can get this all figured out. My programming skills are quite rusty.
