### ISSUE TITLE
Poor visibility on AGS-001

### ISSUE THREAD

**Issue by PrgmrAtHrt** [doomhack/GBADoom#7]
I have been playing this on my GBA-SP (AGS-001), and the game is barely visible. The gamma boost helps very little and washes out the colors.

**Comment by doomhack** [comment]
Yes. I think the solution to this is a custom palette. This is what the commercial ports did.

**Comment by Kippykip** [comment]
When I did my GBA Doom II uncensor hack, I painstakingly went through making unique colour corrected palletes for all gamma levels.
I could make a WAD version with each gamma level as it's own lumps
PLAYPAL1, PLAYPAL2

**Comment by doomhack** [comment]
Yes. I think that is the way to go. We already have a wad file with extra resources.

It can stay in ROM so there is no exta memory requirements.

The current gamma boost code uses a very crude mapping to bump the brightness and also I bump the sector light level slightly.

This causes the colours to be quite washed out though.

**Comment by Kippykip** [comment]
Alrighty, epic.
I'll see if I can go about converting them to Doom's PLAYPAL format and edit the gbadoom.wad with them soon.

**Comment by Kippykip** [comment]
@PrgmrAtHrt Ok so I've made an update to my fork to include the colour corrected lumps ported from that Doom II uncensor hack, and the gamma menu option is a slider now.
I've kept doomhack's sector brightness boost code with the gamma option, but since gamma's a slider it can boost multiple levels now. So it should really help with dark areas on the original GBA model now.

Unfortunately a few years ago I changed my GBA SP to have an AGS-101 screen and board, and my original model GBA screen glue has weakened and made the screen blurry, so I can't actually test this out much on real hardware so I've been using the no$gba emulator with the dark filter.

But I made these palette files back when I had the AGS-001 and original GBA model both working.
I'd love to hear feedback on how it looks now on those models, by my memory the AGS-001 looked best around the middle, while the non-lit original GBA looked best on the max setting.
https://github.com/Kippykip/GBADoom/releases/tag/1_5

@doomhack Here's the commits if you wanna look over it or add it to the main branch.
https://github.com/Kippykip/GBADoom/commits/master

**Comment by PrgmrAtHrt** [comment]
@Kippykip Yup! The middle setting is the magic bullet on the front-lit SP. Also, it looks great now! Thank you so much for this KippyKip!!! 

Thank you both for the promp responce!

**Comment by Kippykip** [comment]
Awesome! ☺

**Comment by doomhack** [comment]
Great work KippyKip.
